import random
def random_names():
    data = {
        "hombres": [
            "juan_perez", "carlos_gomez", "andres_ramirez", "alejandro_fernandez", "diego_morales", "sebastian_rodriguez", 
            "daniel_gutierrez", "santiago_mejia", "nicolas_castro", "jose_gonzalez", "felipe_ruiz", "fernando_padilla", 
            "jorge_lopez", "luis_vega", "mateo_salazar", "javier_herrera", "miguel_torres", "david_martinez", "ricardo_salinas", 
            "manuel_suarez", "cristian_cardenas", "martin_garcia", "leonardo_guzman", "mauricio_mendoza", "francisco_duarte", 
            "pablo_sandoval", "antonio_arias", "gustavo_tapia", "ramiro_montoya", "raul_diaz", "enrique_vargas", 
            "hector_estrada", "rafael_valdez", "alberto_correa", "simon_flores", "omar_rivera", "alvaro_garzon", "brayan_escobar", 
            "ivan_reyes", "angel_ibarra", "adrian_reynoso", "esteban_soto", "emilio_zapata", "tomas_dominguez", 
            "samuel_villanueva", "eduardo_hurtado", "jaime_rios", "rodrigo_acosta", "ernesto_arroyo", "elias_romero", 
            "german_garzon", "julio_ramos", "cesar_flores", "marcos_aquino", "alfredo_salinas", "anibal_vera", 
            "vicente_chavez", "ezequiel_aviles", "oscar_ramirez", "maximiliano_serrano", "gabriel_alcala", "joel_pinto", 
            "sergio_delgado", "lucas_fuentes", "renato_gracia", "teodoro_soto", "ulises_aguilar", "vladimir_rojas", 
            "norberto_acevedo", "humberto_zarate", "fabian_portillo", "ismael_luna", "dario_escalante", "alfonso_peña", 
            "bruno_davila", "cristian_merino", "damian_arias", "efrain_moya", "gregorio_vargas", "hernan_carrillo", 
            "isaac_zavala", "jacobo_lopez", "lorenzo_lozano", "nelson_navarro", "orlando_moreno", "patricio_salinas", 
            "rodolfo_lozano", "saul_moya", "thiago_guerrero", "valentin_cortez", "sergio_rivera", "cristobal_diaz", 
            "felix_villanueva", "nicolas_aguilar", "pedro_pineda", "vicente_mendez", "camilo_serrano", "daniel_aviles", 
            "francisco_lozano", "martin_zapata", "arturo_rangel", "eduardo_flores", "cesar_rios", "edgar_villa", 
            "mateo_salinas", "sebastian_rojas", "andres_tapia", "ramiro_guzman", "raul_reyes", "hernan_diaz", "gonzalo_gomez", 
            "bernardo_suarez", "adolfo_arrieta", "carlos_ibarra", "francisco_morales", "marcelo_peña", "andres_hernandez", 
            "german_gutierrez", "federico_padilla", "humberto_medina", "julio_gomez", "angel_rios", "daniel_morales", 
            "hector_munoz", "adrian_reyes", "ivan_villanueva", "manuel_perez", "raul_zamora", "pablo_lopez", "jose_ramirez", 
            "vicente_villalobos", "rodrigo_santana", "andres_salinas", "felipe_lopez", "joaquin_rojas", "miguel_vega", 
            "eduardo_lopez", "juan_fernandez", "fernando_torres", "david_salinas", "alonso_lopez", "gustavo_torres", 
            "carlos_ramirez", "diego_acosta", "marcos_guzman", "ramon_martinez", "vicente_peña", "cristian_morales", 
            "luis_rodriguez", "santiago_lopez", "fabian_rios", "felipe_ruiz", "camilo_hernandez", "ramiro_garcia", 
            "pedro_fernandez", "sergio_lopez", "gustavo_sandoval", "victor_ramirez", "cesar_gomez", "daniel_ibarra", 
            "rodrigo_cruz", "emilio_lopez", "oscar_pineda", "leonardo_lopez", "ricardo_rojas", "mateo_lopez", 
            "ramiro_villanueva", "raul_cruz", "luis_diaz", "martin_gonzalez", "alvaro_lopez", "pablo_garcia", "victor_cortez", 
            "francisco_salinas", "andres_castro", "eduardo_martinez", "lucas_torres", "felipe_martinez", "luis_alvarez", 
            "raul_moreno", "juanpablo_lopez", "marco_ramirez", "gabriel_lopez", "martin_lopez", "pablo_mendoza", 
            "andres_luna", "alejandro_morales", "angel_ramirez", "sergio_rojas", "felipe_lara", "david_escobar", 
            "pedro_gonzalez", "leonardo_torres", "luis_torres", "gustavo_villanueva", "andres_rodriguez", "daniel_rios", 
            "alberto_serrano", "federico_cruz", "adrian_diaz", "cristian_lopez", "emilio_lopez", "oscar_villanueva", 
            "eduardo_cruz", "felipe_rodriguez", "ramon_morales", "pablo_diaz", "jose_vargas", "sergio_lopez", "leonardo_torres", 
            "victor_cortes", "ricardo_lopez", "alvaro_lopez", "daniel_castro", "fernando_torres", "ramon_fernandez", 
            "pablo_lopez", "camilo_lopez", "carlos_hernandez", "oscar_lopez", "andres_villanueva", "daniel_morales", 
            "alvaro_lopez", "eduardo_lopez", "vicente_torres", "daniel_lopez", "david_salinas", "juan_sanchez", "jose_hernandez", 
            "oscar_diaz", "ricardo_lopez", "mariano_gutierrez", "raul_garcia", "daniel_ruiz", "pablo_gomez", "andres_perez", 
            "sergio_lopez", "daniel_reyes", "eduardo_villa", "luis_moreno", "sergio_hernandez", "alvaro_lopez", 
            "ricardo_lopez", "daniel_pineda", "vicente_vargas", "rodrigo_zapata", "mateo_morales", "gustavo_lopez", 
            "eduardo_pineda", "pablo_villanueva", "daniel_rojas", "felipe_torres", "ricardo_morales", "ramon_mendoza", 
            "david_salinas", "santiago_lopez", "eduardo_lopez", "luis_villanueva", "victor_cortez", "gustavo_lopez", 
            "daniel_villanueva", "alvaro_lopez", "ricardo_torres", "mateo_morales", "oscar_diaz", "pablo_villanueva", 
            "ramon_lopez", "cristian_gomez", "gustavo_rodriguez", "felipe_torres", "emilio_lopez", "raul_villanueva", 
            "eduardo_torres", "victor_gomez", "camilo_lopez", "juanjose_lopez", "cristian_lopez", "daniel_hernandez", 
            "ricardo_morales", "mateo_sandoval", "sergio_lopez", "pablo_ramirez", "fernando_gomez", "daniel_alvarez", 
            "pablo_ramirez", "jose_gomez", "sergio_lopez", "eduardo_villanueva", "david_salinas", "felipe_vega", "gustavo_diaz"
            
        ],"mujeres": [
            "maria_perez", "camila_gomez", "valentina_ramirez", "isabella_fernandez", "sofia_morales", "antonella_rodriguez", 
            "martina_gutierrez", "emilia_mejia", "samantha_castro", "lucia_gonzalez", "juliana_ruiz", "paula_padilla", 
            "diana_lopez", "alejandra_vega", "carolina_salazar", "laura_herrera", "mariana_torres", "daniela_martinez", 
            "gabriela_salinas", "sara_suarez", "melissa_cardenas", "valeria_garcia", "jessica_guzman", "karen_mendoza", 
            "elena_duarte", "ximena_sandoval", "natalia_arias", "andrea_tapia", "angela_montoya", "lina_diaz", "veronica_vargas", 
            "anita_estrada", "constanza_valdez", "rocio_correa", "adriana_flores", "michelle_rivera", "tania_garzon", 
            "yesica_escobar", "katherine_reyes", "fernanda_ibarra", "amanda_reynoso", "marcela_soto", "camila_zapata", 
            "ana_dominguez", "elisa_villanueva", "karina_hurtado", "luisa_rios", "sofia_acosta", "gloria_arroyo", 
            "patricia_romero", "johana_ramos", "laura_flores", "maria_aquino", "claudia_salinas", "elizabeth_vera", 
            "luz_chavez", "nancy_aviles", "flora_ramirez", "milena_serrano", "angelica_alcala", "rosa_pinto", 
            "fatima_delgado", "irma_fuentes", "alicia_gracia", "carla_soto", "margarita_aguilar", "eva_rojas", 
            "nuria_acevedo", "flor_zarate", "miranda_portillo", "irene_luna", "leonor_escalante", "catalina_peña", 
            "maribel_davila", "estefania_merino", "ines_arias", "rebeca_moya", "rosa_vargas", "bianca_carrillo", 
            "clarisa_zavala", "julia_lopez", "pilar_lozano", "rosario_navarro", "aurora_moreno", "viviana_salinas", 
            "carla_lozano", "luisa_moya", "patricia_guerrero", "elena_cortez", "susana_rivera", "ivanna_diaz", 
            "cristina_villanueva", "natalia_aguilar", "reina_pineda", "dora_mendez", "amparo_serrano", "susana_aviles", 
            "judith_lozano", "rosa_zapata", "maribel_rangel", "tatiana_flores", "emilia_rios", "leticia_villa", 
            "marina_salinas", "camila_rojas", "veronica_tapia", "paola_guzman", "romina_tapia", "irene_reyes", 
            "graciela_pineda", "fabiola_fernandez", "sofia_luna", "maria_delgado", "anahi_salinas", "lina_gutierrez", 
            "tamara_arias", "rebeca_herrera", "carmen_cruz", "noemi_guzman", "delfina_tapia", "silvia_garcia", 
            "maria_serrano", "camila_vargas", "sofia_lopez", "emilia_peña", "mariana_santana", "alejandra_pineda", 
            "gabriela_mendez", "daniela_salinas", "luciana_lopez", "miranda_rodriguez", "angelica_villalobos", 
            "aurora_villanueva", "maria_lopez", "gabriela_vargas", "tatiana_torres", "isabel_arias", "paola_reyes", 
            "gloria_pena", "carla_serrano", "ximena_lopez", "camila_gomez", "claudia_lopez", "fernanda_lopez", 
            "maria_diaz", "sara_ibarra", "noemi_rios", "laura_villanueva", "paula_tapia", "maria_fernandez", 
            "romina_salinas", "ana_castro", "gabriela_morales", "alejandra_lopez", "carla_sandoval", "diana_ibarra", 
            "patricia_lopez", "mariana_morales", "anita_lopez", "susana_salinas", "carla_vargas", "maria_tapia", 
            "carolina_cruz", "natalia_garcia", "gabriela_rodriguez", "fernanda_perez", "alejandra_vargas", 
            "claudia_rojas", "maria_arias", "catalina_guerrero", "paola_torres", "flor_salinas", "rosa_ramos", 
            "anahi_pineda", "ximena_guerrero", "melissa_sandoval", "carolina_martinez", "patricia_rodriguez", 
            "valeria_arias", "ana_morales", "delfina_rios", "romina_lopez", "maria_villalobos", "natalia_gutierrez", 
            "maria_rojas", "elena_villalobos", "florencia_rivera", "paola_martinez", "daniela_gonzalez", "alejandra_suarez", 
            "claudia_rodriguez", "isabel_morales", "lina_garcia", "laura_gomez", "maria_castro", "gabriela_zapata", 
            "andrea_ibarra", "valeria_lopez", "elisa_villanueva", "flor_rodriguez", "alejandra_guerrero", "patricia_sandoval", 
            "laura_cruz", "carmen_morales", "luz_diaz", "camila_morales", "elena_gomez", "paola_lopez", "romina_gutierrez", 
            "maria_serrano", "claudia_cruz", "susana_martinez", "maria_garcia", "lucia_salinas", "catalina_rios", 
            "rosa_rodriguez", "paola_morales", "claudia_vargas", "luciana_lopez", "maribel_sandoval", "flor_diaz", 
            "ximena_villanueva", "natalia_rodriguez", "maria_guzman", "camila_lopez", "luz_arias", "diana_fernandez", 
            "lucia_rojas", "natalia_morales", "romina_diaz", "maria_vargas", "alejandra_soto", "fernanda_lopez", 
            "luciana_diaz", "florencia_gomez", "ana_gutierrez", "paola_sandoval", "camila_garcia", "maria_torres", 
            "carolina_lopez", "ximena_rodriguez", "natalia_sandoval", "maria_gutierrez", "flor_guerrero", 
            "claudia_villalobos", "rosa_lopez", "maria_pineda", "paola_cruz", "romina_vega", "natalia_diaz", 
            "alejandra_martinez", "camila_gutierrez", "carla_rodriguez", "maria_arias", "maria_lopez", "rosa_vargas", 
            "diana_salinas", "camila_morales", "natalia_fernandez", "romina_pineda", "ximena_rojas", "maria_guerrero", 
            "valeria_lopez", "catalina_pineda", "laura_salinas", "natalia_lopez", "gabriela_rodriguez", "claudia_morales", 
            "maria_salinas", "lucia_vega", "paola_arias", "romina_diaz", "claudia_soto", "maria_gomez", "luciana_gutierrez", 
            "maria_salinas", "ana_rojas", "rosa_vargas", "natalia_lopez", "maria_diaz", "ximena_rodriguez", "maria_villalobos", 
            "carla_lopez", "paola_salinas", "maria_vargas", "ana_martinez", "claudia_lopez", "romina_rodriguez", 
            "lucia_vargas", "maria_gutierrez", "catalina_martinez", "natalia_lopez", "maria_tapia", "flor_salinas", 
            "romina_lopez", "maria_rodriguez", "paola_morales", "claudia_gutierrez", "maria_perez", "flor_diaz", 
            "romina_morales", "ximena_arias", "ana_morales", "claudia_rodriguez", "lucia_gutierrez", "maria_sandoval", 
            "camila_gutierrez", "ximena_sandoval", "flor_salinas", "claudia_lopez", "maria_tapia", "gabriela_rodriguez", 
            "romina_guerrero", "lucia_rodriguez", "paola_vargas", "natalia_lopez", "gabriela_pineda", "maria_garcia", 
            "lucia_rodriguez", "maria_villalobos", "rosa_gutierrez", "maria_martinez", "ximena_guerrero", "paola_lopez", 
            "catalina_rodriguez", "romina_rojas", "maria_diaz", "ximena_garcia", "rosa_vargas", "gabriela_perez", 
            "ana_gutierrez", "lucia_rodriguez", "paola_guerrero", "ximena_garcia", "catalina_diaz", "romina_lopez", 
            "maria_gomez", "ximena_lopez", "rosa_arias", "lucia_pineda", "gabriela_lopez", "paola_sandoval"
        ]
    }
    name = random.choice(data[random.choice(list(data.keys()))])
    return name.replace("_", "")+"hw"+str(random.randint(1000, 9999)), name.split("_")[0], name.split("_")[1]